name:                scalaz-and-cats
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/fosskers/scalaz-and-cats
license:             BSD3
author:              Colin Woodbury
maintainer:          colin@fosskers.ca
copyright:           2017 - 2018 Colin Woodbury
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - mtl

library:
  source-dirs: src

benchmarks:
  haskell-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -O2
    dependencies:
      - criterion >= 1.1 && < 1.4
      - scalaz-and-cats
      - text
      - text-show
